AWSTemplateFormatVersion: '2010-09-09'
Description: "Cluster template for ECS with Fargate"


#--------------#
#  Parameters  #
#--------------#

Parameters:
  ParentVPCStack:
    Description: 'Parent VPC Stack name.'
    Type: String

  ParClusterName:
    Type: String
    Default: "Cluster"
    Description: "Enter a cluster name"

  DomainName:
    Type: String
    Default: "caprica.tech"
    Description: "Enter the domain name of the project"

  Environment:
    Description: "Select appropriate environment type"
    Type: String
    Default: "prod"
    AllowedValues:
      - non-prod
      - prod

  #---- Tag block parameters ----#
  ParOwner:
    Type: String
    Default: "User"
    Description: "Enter the cluster owner"
  ParProject:
    Type: String
    Default: "DevOps"
    Description: "Enter project name"
  #------------------------------#

  #------------------------------------------#
  # Certificates                             #
  #------------------------------------------#
  PrivateCAArn:
    Type: String
    Description: The ARN of the PrivateCA
    Default: "arn:aws:acm:us-east-1:861211186414:certificate/726e2b03-e2c2-4492-b1ca-80c6303f0862"

      

#--------------#
#  Conditions  #
#--------------#

Conditions:
#  CertificateOverrideTrue: !Equals 
#    - !Ref CertificateOverride
#    - "true"
#
#  CertificateOverrideFalse: !Equals 
#    - !Ref CertificateOverride
#    - "false" 

  IsProdEnv: !Equals
    - !Ref Environment
    - prod
  
  
#--------------#
#  Resources   #
#--------------#

Resources:

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ALBSecurityGroup  
      GroupDescription: Allows inbound traffic to ALB and outbound to ECS Service
      VpcId: {'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'}
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: !If [IsProdEnv, "0.0.0.0/0", "10.0.0.0/16"] 
          FromPort: 80
          ToPort: 80
          Description: "Inbound unencrypted traffic"
        - IpProtocol: tcp
          CidrIp: !If [IsProdEnv, "0.0.0.0/0", "10.0.0.0/16"] 
          FromPort: 80
          ToPort: 443
          Description: "Inbound TLS/encrypted traffic"          
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 49191
          CidrIp: 0.0.0.0/0
          Description: "Egress to ECS Service"
      #---- Resource Tag block ----#
      Tags:
        - Key: "Owner"
          Value: !Ref ParOwner
        - Key: "Project"
          Value: !Ref ParProject
        - Key: "Name"
          Value: "ALB Security Group"
      #----------------------------#


  EcsAlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '30'
      Subnets:
        - {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPublic'}
        - {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetBPublic'}        
        - {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetCPublic'}         
      SecurityGroups:
        - !Ref ALBSecurityGroup
      #---- Resource Tag block ----#
      Tags:
        - Key: "Owner"
          Value: !Ref ParOwner
        - Key: "Project"
          Value: !Ref ParProject
        - Key: "Name"
          Value: "ECS Application Load Balancer"
      #----------------------------#


  AlbSecureListener:
   Type: AWS::ElasticLoadBalancingV2::Listener
   Properties:
     Certificates: 
       - CertificateArn: !Ref PrivateCAArn
     DefaultActions:
     - Type: "fixed-response"
       FixedResponseConfig:
        ContentType: "text/html"
        MessageBody: "We apologise, but this is a nonexistent service"
        StatusCode: "503"
       #TargetGroupArn: !Ref "EcsTg" ## << Placeholder in case one wants to use this directly with TG
     LoadBalancerArn: !Ref EcsAlb
     Port: 443
     Protocol: HTTPS   

  AlbHttplistener: ## << The role of this listener role is to redirect any unencrypted traffic to TLS above
   Type: "AWS::ElasticLoadBalancingV2::Listener"
   Properties:
     DefaultActions:
       - Type: "redirect"
         RedirectConfig:
           Protocol: "HTTPS"
           Port: 443
           Host: "#{host}"
           Path: "/#{path}"
           Query: "#{query}"
           StatusCode: "HTTP_301"
     LoadBalancerArn: !Ref EcsAlb
     Port: 80
     Protocol: "HTTP"


  #---- ECS Cluster block ----#
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ParClusterName
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
      #---- Resource Tag block ----#
      ## Just a different notation example for Tagging
      Tags:
        -
          Key: "Owner"
          Value: !Ref ParOwner
        -
          Key: "Project"
          Value: !Ref ParProject
      #----------------------------#
  #---------------------------#    
          
          
#--------------#
#   Outputs    #
#--------------#

Outputs:

  OutputsEcsCluster:
    Value:
      Ref: EcsCluster
    Export:
      Name: !Sub "${AWS::StackName}-ClusterName"
    Description: "Name of the ECS cluster"
                      
  OutputsAlbArn:
    Value:
      Ref: EcsAlb
    Export:
      Name: !Sub "${AWS::StackName}-EcsAlbArn"
    Description: "ECS ALB ARN"   
    
  OutputsAlbName:
    Value: !GetAtt EcsAlb.LoadBalancerFullName
    Export:
      Name: !Sub "${AWS::StackName}-EcsAlbName"
    Description: "Name of the ECS ALB"
    
  OutputListenerArn:
    Value:
      !Ref AlbSecureListener
    Description: "Listener ARN"  
    Export:
      Name: !Sub "${AWS::StackName}-OutputAlbSecureListener"  
    
  OutputDomainName:
    Value:
      !Ref DomainName
    Description: "The domain name of the project"  
    Export:
      Name: !Sub "${AWS::StackName}-OutputDomainName"  
    
  OutputALBSecurityGroup:
    Value:
      !Ref ALBSecurityGroup
    Description: "Security Group ID of the ALB"
    Export:
      Name: !Sub "${AWS::StackName}-OutputALBSecurityGroup"       